# Generated by Django 3.2.1 on 2021-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_student_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('NO', 'NO'), ('FULL', 'FULL'), ('PART', 'PART')], default='NO', max_length=5),
        ),
    ]
