# Generated by Django 3.1.7 on 2021-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0009_mentor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='photo',
        ),
    ]
