# Generated by Django 3.2.5 on 2021-07-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0011_auto_20210701_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('11:00-12:30', '11:00-12:30'), ('14:00-15:30', '14:00-15:30'), ('16:00-17:30', '16:00-17:30'), ('18:30-20:00', '18:30-20:00')], default='11:00-12:30', max_length=13)),
                ('room', models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('COWORKING', 'COWORKING')], default='FIRST', max_length=12)),
                ('data', models.DateField()),
                ('student_qty', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=90)),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('DONE', 'DONE'), ('CANCEL', 'CANCEL')], default='PLANNED', max_length=8)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboardapp.course')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboardapp.mentor')),
            ],
        ),
    ]
