# Generated by Django 3.2.5 on 2021-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0012_student_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_checkout',
            name='status',
            field=models.CharField(choices=[('TO EXIST', 'TO EXIST'), ('NO', 'NO'), ('CAUSE', 'CAUSE')], default='NO', max_length=8),
        ),
    ]
