# Generated by Django 3.2.5 on 2021-07-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0013_alter_student_checkout_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_checkout',
        ),
    ]
